In [23]:
import numpy as np

In [24]:
import time

In [25]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [26]:
a+b

array([11, 22, 33, 44])

In [27]:
a*b

array([ 10,  40,  90, 160])

In [28]:
a**b

array([              1,         1048576, 205891132094649,               0])

In [29]:
a/b

array([0.1, 0.1, 0.1, 0.1])

In [30]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [32]:
x = np.linspace(-3,3,7)

In [33]:
x

array([-3., -2., -1.,  0.,  1.,  2.,  3.])

In [34]:
np.abs(x)

array([3., 2., 1., 0., 1., 2., 3.])

In [35]:
np.maximum(x,0)

array([0., 0., 0., 0., 1., 2., 3.])

In [36]:
def sigmoid(x):
    return 1./(1.+np.exp(-x))

In [37]:
sigmoid(x)

array([0.04742587, 0.11920292, 0.26894142, 0.5       , 0.73105858,
       0.88079708, 0.95257413])

In [38]:
n = 1_000_000
a = np.random.randn(n)
b = np.random.randn(n)

In [39]:
resultloop = []
start = time.perf_counter()
resultloop = [a[i]+b[i] for i in range(n)]
loop_time = time.perf_counter()-start

In [40]:
start = time.perf_counter()
result_vec = a+b
vec_time = time.perf_counter()-start


In [41]:
print(f"Loop time: {loop_time}, Vec time: {vec_time}")
print(f"Speed up: {loop_time/vec_time}")

Loop time: 0.07911733351647854, Vec time: 0.001236792653799057
Speed up: 63.96976346314296


In [42]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [43]:
mat.sum()

np.int64(45)

In [44]:
mat.sum(axis=0)

array([12, 15, 18])

In [45]:
mat.sum(axis=1)

array([ 6, 15, 24])