In [12]:
import numpy as np

In [13]:
from matplotlib import pyplot as plt

In [14]:
data = np.array([1,2,-1,-4,5])

In [15]:
mask = data > 0

In [16]:
mask

array([ True,  True, False, False,  True])

In [17]:
data[mask]

array([1, 2, 5])

In [18]:
data[~mask]

array([-1, -4])

In [19]:
arr = np.arange(20
                )

In [20]:
arr = arr[(arr>5) & (arr<15)]

In [21]:
arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
labels = np.where(data>0,"pos","neg")
labels

array(['pos', 'pos', 'neg', 'neg', 'pos'], dtype='<U3')

In [23]:
clipped = np.where(data>0,data,0)
clipped

array([1, 2, 0, 0, 5])

In [24]:
vec = np.array([1,2,3])

In [28]:
print(f"Original shape: {vec.shape}")
print(f"Newaxis col: {vec[:,np.newaxis].shape}")
print(f"newaxis row: {vec[np.newaxis,:].shape}")

Original shape: (3,)
Newaxis col: (3, 1)
newaxis row: (1, 3)


In [31]:
mat = np.arange(6).reshape(2,3)
print(mat)
print(mat.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f"vstack: {np.vstack([a,b])}")
print(f"hstack {np.hstack([a,b])}")
print(f"hstack {np.hstack([b,a])}")
print(f"vstack {np.vstack([b,a])}")

vstack: [[1 2 3]
 [4 5 6]]
hstack [1 2 3 4 5 6]
hstack [4 5 6 1 2 3]
vstack [[4 5 6]
 [1 2 3]]
