In [133]:
import numpy as np

In [134]:
import torch

In [135]:
np.set_printoptions(precision=3)

In [136]:
a = [1,2,3]
b = np.array([4,5,6],dtype=np.int32)

In [137]:
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

In [138]:
print(t_a)

tensor([1, 2, 3])


In [139]:
print(t_b)

tensor([4, 5, 6], dtype=torch.int32)


In [140]:
t_ones = torch.ones(2,3)

In [141]:
t_ones.shape

torch.Size([2, 3])

In [142]:
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [143]:
rand_tensor = torch.rand(2,3)

In [144]:
print(rand_tensor)

tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]])


In [145]:
t_a_new = t_a.to(torch.int64)

In [146]:
print(t_a_new.dtype)

torch.int64


In [147]:
t=torch.rand(3,5)

In [148]:
t_tr = torch.transpose(t,0,1)

In [149]:
t.shape

torch.Size([3, 5])

In [150]:
t_tr.shape

torch.Size([5, 3])

In [151]:
t = torch.ones(1,2,1,4,1)

In [152]:
t

tensor([[[[[1.],
           [1.],
           [1.],
           [1.]]],


         [[[1.],
           [1.],
           [1.],
           [1.]]]]])

In [153]:
t.shape

torch.Size([1, 2, 1, 4, 1])

In [154]:
t_sqz = torch.squeeze(t,2)

In [155]:
t_sqz

tensor([[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]])

In [156]:
t_sqz.shape

torch.Size([1, 2, 4, 1])

In [157]:
torch.manual_seed(1)

In [158]:
t1 = 2*torch.rand(5,2)-1

In [159]:
t2 = torch.normal(mean=0,std=1,size=(5,2))

In [160]:
t3 = torch.multiply(t1,t2)

In [161]:
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [162]:
t4 = torch.mean(t1,axis=0)

In [163]:
t4

tensor([-0.1373,  0.2028])

In [164]:
torch.mean(t1,axis=1)

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])

In [165]:
t5 = torch.matmul(t1,torch.transpose(t2,0,1))
t5

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])

In [166]:
x = torch.tensor([[1,2,3],
                  [4,5,6]])

In [167]:
x.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [168]:
torch.transpose(x,1,1)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [169]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [170]:
t1

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

In [171]:
norm_t1 = torch.linalg.norm(t1,ord=2,dim=1)
norm_t1

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

In [172]:
torch.manual_seed(1)
t = torch.rand(6)

In [173]:
t

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])

In [174]:
t_splits = torch.chunk(t,3)

In [175]:
t_splits

(tensor([0.7576, 0.2793]), tensor([0.4031, 0.7347]), tensor([0.0293, 0.7999]))

In [180]:
torch.manual_seed(1)
t = torch.rand(5)

In [181]:
t_splits = torch.split(t,split_size_or_sections=[3,2])
t_splits

(tensor([0.7576, 0.2793, 0.4031]), tensor([0.7347, 0.0293]))